singleQuote: true
overrides:
  - files: ['*.yml', '*.yaml']
    options:
      parser: yaml
  - files: '*.json'
    options:
      parser: json
      trailingComma: none
  - files: '*.md'
    options:
      parser: markdown
