name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      [
        '.github/workflow/release.yml',
        '.changeset/*.md',
        '**/package.json',
        'pnpm-lock.yaml',
      ]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - run: pnpm i --ignore-scripts
      - run: pnpm build

      - name: Create Release PR or Publish
        uses: changesets/action@v1
        with:
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # https://stackoverflow.com/a/69169858/9771158
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
